AWSTemplateFormatVersion: '2010-09-09'
Description: A CloudFormation template to deploy a Django application on EC2.

Parameters:
  Environment:
    Type: String
    Default: Development
    AllowedValues:
      - Development
      - Staging
      - Production
    Description: Environment type for resource tagging
  
  ApplicationName:
    Type: String
    Default: DjangoApp
    Description: Name of the application for resource tagging
  
  S3BucketName:
    Type: String
    Description: S3 bucket name for static assets and media storage. Must follow S3 bucket naming rules.
    Default: my-django-app-assets

Resources:
  # Security Group to Allow SSH, HTTP, and HTTPS Access
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and HTTPS access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # SSH Access (port 22)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # HTTP Access (port 80)
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # HTTPS Access (port 443)
      Tags:
        - Key: Name
          Value: !Sub "${ApplicationName}-SecurityGroup"
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Role for EC2 Instance with specific permissions
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Policies:
        - PolicyName: SpecificS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: 
                  - !Sub "arn:aws:s3:::${S3BucketName}"
                  - !Sub "arn:aws:s3:::${S3BucketName}/*"
      Tags:
        - Key: Name
          Value: !Sub "${ApplicationName}-Role"
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation

  # Instance Profile for the IAM Role
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: 
        - !Ref EC2InstanceRole

  # EC2 Instance
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: "my-key"
      ImageId: "ami-0c55b159cbfafe1f0"
      UserData:
        Fn::Base64: |
          #!/bin/bash
          apt-get update -y
          apt-get install -y python3-pip docker.io git
          systemctl start docker
          systemctl enable docker
          git clone https://github.com/Nehad-Said/Unlimited-Subcategories.git
          cd Unlimited-Subcategories
          docker-compose up -d
      Tags:
        - Key: Name
          Value: !Sub "${ApplicationName}-Server"
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: ManagedBy
          Value: CloudFormation
        - Key: Owner
          Value: DevOps
        - Key: CostCenter
          Value: IT-Infrastructure

Outputs:
  InstancePublicIP:
    Description: The public IP of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
  SSHCommand:
    Description: Command to connect to the instance via SSH
    Value: !Sub "ssh -i KEY_PAIR.pem ubuntu@${EC2Instance.PublicDnsName}"
  Environment:
    Description: Deployment environment
    Value: !Ref Environment
